# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tutorials.models.user_course


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=9)),
                ('mail', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('gplus', models.URLField()),
                ('terms', models.TextField()),
                ('info', models.TextField()),
                ('active_configuration', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=32, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('has_certificate', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_with_certificate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('visible', models.BooleanField(default=True)),
                ('certificate_title', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_background', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField()),
                ('finished', models.BooleanField()),
                ('success', models.BooleanField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=32, null=True)),
                ('is_icon_visible', models.BooleanField(default=False)),
                ('is_name_visible', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short', models.TextField()),
                ('text', models.TextField()),
                ('visible', models.BooleanField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('invoice_generated', models.BooleanField(default=False)),
                ('invoice_sent', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[(b'S', b'Pytanie jednokrotnego wyboru'), (b'M', b'Pytanie wielokrotnego wyboru'), (b'O', b'Pytanie otwarte')], default=b'S', max_length=1)),
                ('answer_a', models.TextField()),
                ('answer_b', models.TextField()),
                ('answer_c', models.TextField()),
                ('answer_d', models.TextField()),
                ('open_answer', models.TextField()),
                ('is_answer_a_correct', models.BooleanField()),
                ('is_answer_b_correct', models.BooleanField()),
                ('is_answer_c_correct', models.BooleanField()),
                ('is_answer_d_correct', models.BooleanField()),
                ('points', models.IntegerField(default=1)),
                ('visible', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Course')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('answered', models.BooleanField()),
                ('success', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('has_to_answer_questions', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Course')),
                ('questions', models.ManyToManyField(to='tutorials.Question')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('with_certificate', models.BooleanField(default=False)),
                ('course_completed', models.BooleanField(default=False)),
                ('exam_passed', models.BooleanField(default=False)),
                ('certificate_generated', models.BooleanField(default=False)),
                ('certificate_sent', models.BooleanField(default=False)),
                ('time_limit', models.DateTimeField(default=tutorials.models.user_course.get_course_time_limit)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Course')),
                ('current_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.Topic')),
                ('exam_takes', models.ManyToManyField(to='tutorials.ExamTake')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=32)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('during_password_reset', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('nip', models.CharField(blank=True, max_length=10, null=True)),
                ('business_name', models.TextField(blank=True, null=True)),
                ('invoice_address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usercourse',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.UserInfo'),
        ),
        migrations.AddField(
            model_name='questiontake',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.UserInfo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.UserInfo'),
        ),
        migrations.AddField(
            model_name='examtake',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.UserInfo'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(to='tutorials.Question'),
        ),
    ]
