# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='active',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_icon_visible',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_name_visible',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='title',
        ),
        migrations.AddField(
            model_name='menu',
            name='for_guest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='for_logged_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='for_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='ident',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ident',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='module',
            name='ident',
            field=models.CharField(max_length=32),
        ),
    ]
