# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20170909_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('internal_link', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_link_text', models.CharField(blank=True, max_length=255, null=True)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('external_link_text', models.CharField(blank=True, max_length=255, null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='gplus',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
