# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_notice_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='contact_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
