# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_c',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_answer_a_correct',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_answer_b_correct',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_answer_c_correct',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_answer_d_correct',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='open_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
