# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_questiontake_exam_take'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
