# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_remove_usercourse_exam_takes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='for_guest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='for_logged_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='for_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
