# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_auto_20170910_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='active',
            new_name='visible',
        ),
    ]
