# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tutorials.models.new


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0013_auto_20170910_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='short',
        ),
        migrations.AddField(
            model_name='new',
            name='author',
            field=models.ForeignKey(default=tutorials.models.new.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
