# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0018_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_token',
            field=models.CharField(default='a', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='vat',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
