# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0019_auto_20171012_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='regon',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
