# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0020_userinfo_regon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
