# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-14 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0022_auto_20171012_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
