# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-14 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0023_auto_20171014_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='invoice_account',
            field=models.BooleanField(default=False),
        ),
    ]
