const ACTIONS = {
  APP_NAVIGATE: Symbol('ACTIONS.APP_NAVIGATE'),
  APP_ADD_ERROR: Symbol('ACTIONS.APP_ADD_ERROR'),
  APP_DELETE_ALL_ERRORS: Symbol('ACTIONS.APP_DELETE_ALL_ERRORS'),
  APP_DELETE_ERROR: Symbol('ACTIONS.APP_DELETE_ERROR'),
  APP_ADD_NOTICE: Symbol('ACTIONS.APP_ADD_NOTICE'),
  APP_DELETE_ALL_NOTICES: Symbol('ACTIONS.APP_DELETE_ALL_NOTICES'),
  APP_DELETE_NOTICE: Symbol('ACTIONS.APP_DELETE_NOTICE'),
};


export {
  ACTIONS
};
